{
	"version": 1734333470,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/bomb-sheet0.png",
		"images/bomb-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/memesnakeassetslost-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/asset14x-sheet0.png",
		"images/asset14x-sheet1.png",
		"images/asset14x-sheet2.png",
		"images/asset14x-sheet3.png",
		"images/asset14x-sheet4.png",
		"images/asset14x-sheet5.png",
		"media/meme_1.m4a",
		"media/meme_1.ogg",
		"media/meme_2.m4a",
		"media/meme_2.ogg",
		"media/meme_3.m4a",
		"media/meme_3.ogg",
		"media/meme_4.m4a",
		"media/meme_4.ogg",
		"media/meme_0.m4a",
		"media/meme_0.ogg",
		"media/yayyy.m4a",
		"media/yayyy.ogg",
		"media/meme snake - bgm.m4a",
		"media/meme snake - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}